env:
  es6: true
  browser: true
  webextensions: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  valid-jsdoc:
    - error
    - requireReturn: false
      requireReturnDescription: false
