extends: stylelint-config-standard
plugins:
	- stylelint-order
rules:
  color-hex-case: upper
  declaration-no-important: true
  order/order:
    - type: at-rule
      hasBlock: false
    - dollar-variables
    - custom-properties
    - declarations
    - rules
  order/properties-order:
    -
      - groupName: Content
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - content
      - groupName: Font & Text
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - color
          - font
          - font-family
          - font-size
          - line-height
          - font-style
          - font-weight
          - font-variant
          - text-decoration
          - text-decoration-color
          - text-decoration-line
          - text-decoration-style
          - text-underline-position
          - text-emphasis
          - text-emphasis-color
          - text-emphasis-position
          - text-emphasis-style
          - text-transform
          - white-space
          - hyphens
          - word-break
          - word-spacing
      - groupName: Box Model
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - display
          - box-sizing
          - width
          - height
          - min-width
          - max-width
          - min-height
          - max-height
          - margin
          - margin-top
          - margin-right
          - margin-bottom
          - margin-left
          - padding
          - padding-top
          - padding-right
          - padding-bottom
          - padding-left
          - overflow
          - overflow-x
          - overflow-y
          - overflow-wrap
          - resize
      - groupName: Position
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - position
          - top
          - right
          - bottom
          - left
          - z-index
          - float
          - clear
      - groupName: Grid
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - grid
          - grid-template
          - grid-template-columns
          - grid-template-rows
          - grid-template-areas
          - grid-auto-rows
          - grid-row
          - grid-row-end
          - grid-row-start
          - grid-auto-columns
          - grid-column
          - grid-column-end
          - grid-column-start
          - grid-auto-flow
          - grid-gap
          - grid-row-gap
          - grid-column-gap
          - gap
          - row-gap
          - column-gap
          - grid-area
      - groupName: Flex
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - flex
          - flex-grow
          - flex-shrink
          - flex-basis
          - flex-flow
          - flex-direction
          - flex-wrap
          - order
          - place-items
          - place-content
          - place-self
          - align-items
          - align-content
          - align-self
          - justify-items
          - justify-content
          - justify-self
      - groupName: Text layout
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - letter-spacing
          - text-indent
          - text-justify
          - text-align
          - text-align-last
          - direction
          - unicode-bidi
          - writing-mode
          - text-orientation
          - text-combine-upright
          - text-overflow
          - text-shadow
      - groupName: Background
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - background
          - background-attachment
          - background-clip
          - background-color
          - background-image
          - background-origin
          - background-position
          - background-position-x
          - background-position-y
          - background-repeat
          - background-size
      - groupName: Border
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - border
          - border-width
          - border-style
          - border-color
          - border-top
          - border-top-style
          - border-top-width
          - border-top-color
          - border-right
          - border-right-style
          - border-right-width
          - border-right-color
          - border-bottom
          - border-bottom-style
          - border-bottom-width
          - border-bottom-color
          - border-left
          - border-left-style
          - border-left-width
          - border-left-color
          - border-radius
          - border-top-left-radius
          - border-top-right-radius
          - border-bottom-left-radius
          - border-bottom-right-radius
          - box-shadow
          - outline
          - outline-style
          - outline-width
          - outline-color
          - outline-offset
          - border-image
          - border-image-source
          - border-image-width
          - border-image-repeat
          - border-image-slice
          - border-image-outset
      - groupName: Animation
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - animation
          - animation-name
          - animation-duration
          - animation-timing-function
          - animation-delay
          - animation-iteration-count
          - animation-direction
          - animation-fill-mode
          - animation-play-state
      - groupName: Transition
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - transition
          - transition-property
          - transition-duration
          - transition-timing-function
          - transition-delay
      - groupName: Transformation
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - transform
          - transform-origin
          - transform-box
          - transform-style
          - perspective
          - perspective-origin
          - backface-visibility
      - groupName: SVG
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - pointer-events
          - fill
          - fill-opacity
          - fill-rule
          - stroke
          - stroke-width
          - stroke-opacity
          - stroke-linecap
          - stroke-linejoin
          - stroke-miterlimit
          - stroke-dasharray
          - stroke-dashoffset
          - paint-order
          - clip-path
          - mask
          - mask-image
          - mask-mode
          - mask-repeat
          - mask-position
          - mask-clip
          - mask-origin
          - mask-size
          - mask-composite
          - mask-type
          - mask-border
          - mask-border-source
          - mask-border-slice
          - mask-border-width
          - mask-border-outset
          - mask-border-repeat
          - mask-border-mode
      - groupName: Columns
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - columns
          - column-width
          - column-count
          - column-gap
          - column-fill
          - column-span
          - column-rule
          - column-rule-color
          - column-rule-style
          - column-rule-width
      - groupName: List & Counter
        emptyLineBefore: always
        noEmptyLineBetween: true
        properties:
          - list-style
          - list-style-type
          - list-style-image
          - list-style-position
          - counter-set
          - counter-increment
          - counter-reset
    - unspecified: bottomAlphabetical
      emptyLineBeforeUnspecified: always
